name: Rebase onto Fork

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 12 * * *'
  
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Attempting fork rebase!
      - name: Run a multi-line script
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          git fetch
          git pull --unshallow
          
          git remote add poucave https://github.com/mozilla-services/poucave.git
          git fetch poucave
          git pull --rebase poucave main

          git push --force origin main
          
          git checkout main-release
          git reset --hard main
          git push --force origin main-release

